### ISSUE TITLE
Error when enabling Antlers Toolbox

### ISSUE THREAD

**Issue by CjRootStudio** [Stillat/vscode-antlers-language-server#41]
**Describe the bug**
When enabling Antlers Toolbox in VS Code, I receive 2 errors:

_A request has failed. See the output for more information._

_The Antlers Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted._

Checking the console in VSCode, I see the following:

`YAMLReferenceError: Aliased anchor not found: 
    at resolveNodeValue (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/node_modules/yaml/dist/resolveSeq-d03cb037.js:1568:19)
    at Object.resolveNode (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/node_modules/yaml/dist/resolveSeq-d03cb037.js:1629:15)
    at parseContents (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/node_modules/yaml/dist/Document-9b4560a1.js:357:30)
    at Document.parse (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/node_modules/yaml/dist/Document-9b4560a1.js:615:5)
    at parseDocument (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/node_modules/yaml/dist/index.js:44:37)
    at Object.parse (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/node_modules/yaml/dist/index.js:55:15)
    at getBlueprintFields (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/out/projects/fileSystemProvider/blueprints.js:77:87)
    at getProjectStructure (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/out/projects/fileSystemProvider/fileSystemStatamicProject.js:404:74)
    at collectProjectDetails (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/out/server.js:294:152)
    at contentChangeHandler (/Users/cj/.vscode/extensions/stillat-llc.vscode-antlers-2.3.1/server/out/server.js:205:5) {
  source: Alias {
    error: null,
    range: Range { start: 0, end: 1 },
    valueRange: Range { start: 1, end: 1 },
    props: [],
    type: 'ALIAS',
    value: null,
    resolved: null
  }
}
[Error - 9:29:40 AM] Connection to server got closed. Server will not be restarted.`

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

Antlers Toolbox for VS Code

**Versions and Other Plugins/Extensions**

_VS Code_ - Version 1.68.1

_Antlers Toolbox_ - v2.3.1

**To Reproduce**

When first enabling the Antlers Toolbox add-on. No other add-ons enabled.

**Comment by JohnathonKoster** [comment]
Additional guards have been added to the built-in YAML parser, and has been resolved with the following versions:

* Antlers Toolbox for VS Code: 2.3.2
* `antlers-language-server`: 1.0.7 (standalone)
